import RootStore from './containers/RootStore';
import './globals.css';

export const metadata = {
  title: 'Todo Demo - Redux',
  description: 'Generated by create next app',
};

export default function RootLayout(
  { children }: { children: React.ReactNode },
) {
  return (
    <html lang="en">
      <body>
        <RootStore>
          {children}
        </RootStore>
      </body>
    </html>
  );
}
