name: Auto Test and Test Coverage

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/devcontainers/typescript-node:0-18 # replace this with your docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Run Test Coverage
        run: npm run test-coverage
